Table CLIENTE {
	id_cliente integer [ pk, increment, not null, unique ]
	nombre varchar
	telefono varchar
}

Table servicio {
	id_servicio integer [ pk, increment, not null, unique ]
	nombre varchar
	precio varchar
	duracion timestamp
	id_cliente integer
}

Table cita {
	id_cita integer [ pk, increment, not null, unique ]
	fecha y hora timestamp
	id_profesional integer
	id_servicios integer
}

Table detalle de cita {
	id_cita integer
	id_detalle integer
	id_sercicio integer
	observacion varchar
}

Table profesional {
	id_profesional integer [ pk, increment, not null, unique ]
	nombre varchar
	especial varchar
	horario timestamp
	id_cita integer
}

Table factura {
	id_factura integer [ pk, increment, not null, unique ]
	id_cita integer
	fecha date
	forma de pagototal decimal
	total decimal
}

Ref fk_CLIENTE_id_cliente_servicio {
	CLIENTE.id_cliente < servicio.id_cliente [ delete: restrict, update: cascade ]
}

Ref fk_servicio_id_servicio_cita {
	servicio.id_servicio < cita.id_cita [ delete: restrict, update: cascade ]
}

Ref fk_cita_id_cita_detalle de cita {
	cita.id_cita < detalle de cita.id_cita [ delete: restrict, update: cascade ]
}

Ref fk_detalle de cita_id_cita_profesional {
	detalle de cita.id_cita < profesional.id_cita [ delete: restrict, update: cascade ]
}

Ref fk_profesional_id_cita_factura {
	profesional.id_cita < factura.id_cita [ delete: restrict, update: cascade ]
}